### ISSUE TITLE
Module Broken

### ISSUE THREAD

**Issue by donafcna** [ProfessorAire/ElegantXML-Crestron#10]
Good afternoon,
I am testing the module on a Crestron RMC3 processor. After each upload, the RMC3 automatically deletes the file. Looking at the logs on the processor I can see an issue with the HTTP request (see below). Following my call, could you please check if it is possible to upgrade the module? 

 
Error: splusmanagerapp.exe [App 1] # 2000-12-04 00:19:18  # SplusManagerApp: Got unhandled exception System.NullReferenceException: NullReferenceException
   at ControlhausSIMPLSharpLibraryDoorbird.SimplSharpDoorbirdCommunications.OnHTTPClientResponseCallback(HttpClientResponse response, HTTP_CALLBACK_ERROR errorError: splusmanagerapp.exe # 2000-12-04 00:19:18  # Exception: App 1 - SPLUS Repriotizer Thread Exiting - System.Threading.ThreadAbortException: ThreadAbortException
   at System.Threading.EventWaitHandle.WaitOne()
   at Amib.Threading.SmartThreadPool.y()

Error: splusmanagerapp.exe [App 1] # 2000-12-04 00:19:18  # SimplPlus: Got exception System.Threading.ThreadAbortException: ThreadAbortException
   at Crestron.Logos.SplusManager.SplusManager..ctor(String appName, UInt32 nv, UInt32 appNumber, Int32 initialLogicPriorityToBaseOff)
   at fg.b(String[] A_0)

**Comment by ProfessorAire** [comment]
This error is completely unrelated to this project.
